### ISSUE TITLE
Log categories

### ISSUE THREAD

**Issue by Naotocchi** [MirageAegis/Sushi-Bot#32]
# Feature Request
Categories for the log to be sorted into, such as messages (edited, deleted) and people joining/leaving the server.

## Acceptance Criteria
- [x] Sushi bot shall have 3 different categories, and they should be named:
  - [x] Messages
  - [x] Members
  - [x] Profiles
- [x] Sushi bot shall let server administrators opt in or out of different categories.

## Additional Context
For the sake of not flooding the log chat with unimportant log messages and to make it easier for server administrators to keep track of what's happening while they're gone.

**Comment by MirageAegis** [comment]
I'll work on this as soon as the reaction roles have been merged!

**Comment by MirageAegis** [comment]
Change of plans. This issue will be worked on in the `reaction-roles` branch
